M48
; DRILL file KiCad 10.0.1 date 2026-09-07T02:54:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T02:54:54+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X118.08Y-92.18
X123.86Y-92.18
T2
X159.785Y-84.97
X159.785Y-91.97
T3
X190.14Y-81.45
X190.14Y-94.15
M30
