M48
; DRILL file {KiCad 7.0.2} date Wed 25 Oct 03:12:17 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-25T03:12:17+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X118.08Y-92.18
X123.86Y-92.18
T2
X159.785Y-84.97
X159.785Y-91.97
T3
X190.14Y-81.45
X190.14Y-94.15
T0
M30
